GROQ_API_KEY="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"

SENTENCES_TRANSFORMER_MODEL=all-MiniLM-L6-v2

SUPABASE_URL=https://ylwayeqyxqkdpbndcrzl.supabase.co
SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsd2F5ZXF5eHFrZHBibmRjcnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyODMyNzIsImV4cCI6MjA5Nzg1OTI3Mn0.o2xe9HInYBQxjgSdlxcUuGDw1I4yjRJIbJ8e0RVSOCY
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsd2F5ZXF5eHFrZHBibmRjcnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyODMyNzIsImV4cCI6MjA5Nzg1OTI3Mn0.o2xe9HInYBQxjgSdlxcUuGDw1I4yjRJIbJ8e0RVSOCY
AUTH_REDIRECT_URL=http://localhost:8501