[backend]
url=http://localhost:8000

[supabase]
SUPABASE_URL=https://ylwayeqyxqkdpbndcrzl.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsd2F5ZXF5eHFrZHBibmRjcnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyODMyNzIsImV4cCI6MjA5Nzg1OTI3Mn0.o2xe9HInYBQxjgSdlxcUuGDw1I4yjRJIbJ8e0RVSOCY

[google_oauth]
client_id=889031057033-p9d55btsp234lmhudsbmrrun7hhgf2fp.apps.googleusercontent.com
client_secret=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
REDIRECT_URL=http://localhost:8501